### ISSUE TITLE
GeolocateControl 

### ISSUE THREAD

**Issue by Jinksi** [uber/react-map-gl#388] opened 2017-10-21 04:53 UTC
Are there any plans to include the GeolocateControl?

https://www.mapbox.com/mapbox-gl-js/api/#geolocatecontrol

**Comment by Pessimistress** [comment] 2018-08-05 22:35
Duplicate of https://github.com/uber/react-map-gl/issues/484

**Closed by Pessimistress** 2018-08-05 22:35 UTC
