### ISSUE TITLE
Can't interact with maps on iPhone

### ISSUE THREAD

**Issue by cezary** [uber/react-map-gl#68] opened 2016-04-08 23:40 UTC
Maps don't move when dragged on mobile Safari (might affect Android browsers as well). This is because react-map-gl only responds to mouse events; quick fix may be to add listeners for touch events.

**Comment by kachkaev** [comment] 2016-08-02 08:17
@cezary were you able to generate some workaround? Would be good to have some temporal solution until the issue is solved in the repo.

**Comment by cammanderson** [comment] 2016-08-02 19:44
Hi guys, there is a pull request that adds support for touch. Just waiting on it to be approved.

**Comment by forrert** [comment] 2016-10-14 00:01
For me panning and zooming on mobile devices still does not work. I'm working with version `1.6.1` of this module. 

An easy way to reproduce this issue would be to go to http://uber.github.io/react-map-gl/#/interactivity and open the developer tools in Chrome and 'Toggle device toolbar' to view the page in a mobile device. This makes panning impossible. 

I was able to get the touch events working by adding the following line after the map object is initialized:

      map.touchZoomRotate.enable();

I would be happy to submit a pull request that implements this, by exposing the settings on these [handlers](https://www.mapbox.com/mapbox-gl-js/api/#Handlers) through props.

**Comment by Apercu** [comment] 2016-12-03 03:36
Hey @cammanderson, this has been resolved by https://github.com/uber/react-map-gl/pull/101 right?

**Comment by cammanderson** [comment] 2016-12-03 03:37
Correct.

**Comment by Apercu** [comment] 2016-12-03 03:38
Thanks

**Closed by Apercu** 2016-12-03 03:38 UTC
Labels: bug
