### ISSUE TITLE
Providing Custom Sources/Layers via mapStyle Causes Blank Map

### ISSUE THREAD

**Issue by jimjkelly** [uber/react-map-gl#152] opened 2016-11-17 01:13 UTC
As the subject says, this causes a blank map.  One can see this actually on the main documentation page:

https://uber.github.io/react-map-gl/#/

At the bottom, when discussing custom mapStyles, there is nothing displayed.

**Comment by jefffriesen** [comment] 2016-11-20 15:44
Here is another example in the documentation: https://uber.github.io/react-map-gl/#/scatterplot

Here are the errors in the console:
> bundle.js:2354 Mixed Content: The page at 'https://uber.github.io/react-map-gl/#/scatterplot' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tile.stamen.com/toner/12/654/1583.png'. This request has been blocked; the content must be served over HTTPS.

> bundle.js:2354 XMLHttpRequest cannot load http://tile.stamen.com/toner/12/654/1583.png. Failed to start loading.

@jimjkelly would it be possible to request the stamen tile over https?

**Comment by Apercu** [comment] 2016-12-03 07:30
Dupe of https://github.com/uber/react-map-gl/issues/80

**Closed by Apercu** 2016-12-03 07:30 UTC
Labels: duplicate
