### ISSUE TITLE
none of the examples in example folder are working ...

### ISSUE THREAD

**Issue by hemedani** [uber/react-map-gl#534] opened 2018-06-24 07:39 UTC
It' throw several error like this :
```bash
ERROR in ./src/root.js
Module build failed: ReferenceError: Unknown plugin "version-inline" specified in "/Users/syd/work/GitRepo/react-map-gl/.babelrc" at 0, attempted to resolve relative to "/Users/syd/work/GitRepo/react-map-gl"
    at /Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/syd/work/GitRepo/react-map-gl/examples/geojson/node_modules/babel-loader/lib/index.js:163:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/root.js
```
and this ::
```bash
ERROR in ./view.js
Module not found: Error: Can't resolve 'react-map-gl' in '/Users/syd/work/GitRepo/react-map-gl/examples/deckgl-overlay'
 @ ./view.js 24:0-44
 @ ./app.js
 @ ./root.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./root.js
```

please check the example folder
best regard

**Comment by ibgreen** [comment] 2018-06-25 13:36
> Module not found: Error: Can't resolve 'react-map-gl'

Example works for me... Did you install dependencies before you started the app (i.e. did you run `yarn` or `npm install`)?

> Module build failed: ReferenceError: Unknown plugin "version-inline"

This first error will likely go away if you install in the root folder. But that shouldn't be needed, so marking this as a bug.

While we should keep master working, in worst case, to unblock yourself, try to checkout a previous release branch `3.2-release` and run exampled from there.

**Comment by wafisher** [comment] 2018-08-28 04:59
I'm also running into this, even on 3.2. More importantly, is there a good way to see the deck.gl examples in action?

Steps to reproduce:

```
cd react-map-gl
npm install
export MapboxAccessToken=[...]
npm run start
```

This launches a website at `localhost:8081` which has the examples but there are some styling issues and the deck.gl examples aren't in there.

**Comment by HeiYanjing** [comment] 2018-09-28 02:55
I got the same error ,in react-map-gl: i tried 'yarn install ' and 'npm install' .
and set the mapbox access token.
but 
```
ERROR in ./view.js
Module not found: Error: Can't resolve 'react-map-gl' in 'E:\webglsample\react-map-gl\examples\deckgl-overlay'
 @ ./view.js 24:0-44
 @ ./app.js
 @ ./root.js
 @ multi (webpack)-dev-server/client?http://localhost:8083 webpack/hot/dev-server ./root.js

```

**Comment by Pessimistress** [comment] 2018-10-04 18:42
Examples on both the 3.3-release branch (using babel 6 + webpack 2) and the master branch (using babel 7 + webpack 4) are updated. Let us know if you still experience issues running them locally.

**Closed by Pessimistress** 2018-10-04 18:42 UTC
Labels: bug
