### ISSUE TITLE
NavigationControl doesn't work with deck.gl 7.3.11

### ISSUE THREAD

**Issue by goszczynskip** [uber/react-map-gl#973] opened 2020-01-02 15:04 UTC
I'm getting error `TypeError: this._context.map is undefined`. It looks like https://github.com/uber/react-map-gl/commit/f73b467d81fa379ff3a69e688b59fd97e70b769b#diff-5a20ea8b2d2eb1fc6fc9559a53507105R146 broke it. `map` isn't present in the context. In context following keys are present: `viewport`, `container`, `eventManager`, `onViewStateChange`.

### Usage

```
      <DeckGL
        viewState={viewState}
        controller={{ type: MapController, dragRotate: false }}
        height={"100%"}
        width={"100%"}
        layers={layers}
        onViewStateChange={setViewState}
        ContextProvider={MapContext.Provider}
      >
        <StaticMap mapStyle={runtimeEnv.REACT_APP_TILES_PROVIDER_URL}>
          {children}
        </StaticMap>
        <NavigationsContainer>
          <NavigationControl />
        </NavigationsContainer>
      </DeckGL>
```

**Comment by Pessimistress** [comment] 2020-01-02 21:31
Fixed in 5.1.7

**Closed by Pessimistress** 2020-01-02 21:31 UTC

**Comment by MehdiSaffar** [comment] 2020-03-30 10:06
I am trying to overlay both the navigation control and MapboxGeocoder. Could you tell me what that NavigationsContainer is? I can't find it. @goszczynskip

**Comment by goszczynskip** [comment] 2020-03-30 10:37
It's my custom component
```
export const NavigationsContainer = styled.div`
  z-index: 1;
  position: absolute;
  left: ${props => props.theme.spacing(1)}px;
  bottom: ${props => props.theme.spacing(1)}px;
`;
```

**Comment by MehdiSaffar** [comment] 2020-03-30 10:43
Oh okay, have you tried using MapboxGeocoder? It add the search bar. the problem is that the search bar appears but I can't interact with it since the deck.gl is putting some div over the whole map section so it intercepts the click. The way I am doing it is like this:

```
    const map = useRef()

    useEffect(() => {
        if (!map.current) return
        const m = map.current.getMap()
        if (!m) return
        m.addControl(new MapboxGeocoder({
            accessToken: config.mapboxAccessToken,
            mapboxgl: map.current._mapbox.mapboxgl
        }))
    }, [map.current])


    return ( <div className={cls(className)}>
            <DeckGL
                getCursor={getCursor}
                viewState={viewState}
                controller={controller}
                onViewStateChange={onViewStateChange}
                layers={glLayers}
            >
                <StaticMap
                    ref={map}
                    mapboxApiAccessToken={config.mapboxAccessToken}
                    mapStyle={mapStyle.url}>
                </StaticMap>
            </DeckGL>
        </div>);
```

and it looks like this:

![image](https://user-images.githubusercontent.com/13124263/77903951-5f6a2080-728c-11ea-903e-25f2b69cee7a.png)
